CREATE TABLE `invoiceArchive` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`fileUrl` varchar(512) NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileType` enum('pdf','xml','efactura','other') DEFAULT 'pdf',
	`fileSize` int,
	`invoiceNumber` varchar(100),
	`supplierName` varchar(255),
	`supplierCUI` varchar(20),
	`issueDate` varchar(20),
	`dueDate` varchar(20),
	`total` decimal(12,2),
	`totalVAT` decimal(12,2),
	`currency` varchar(3) DEFAULT 'RON',
	`source` enum('smartbill','oblio','fgo','spv_anaf','efactura','pdf_manual','xml_manual','other') DEFAULT 'pdf_manual',
	`status` enum('pending','processed','refactured','archived') DEFAULT 'pending',
	`reInvoiceId` int,
	`notes` text,
	`tags` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoiceArchive_id` PRIMARY KEY(`id`)
);
