/**
 * Plan de Conturi SAGA — Generat din export XLSX SAGA C Web Test
 * Sursa: web0.sagasoft.ro/test/PlanConturi
 * Total: 583 conturi
 */

export interface SagaCont {
  cod: string;
  denumire: string;
  tip: "A" | "P" | "B";
}

export const SAGA_PLAN_CONTURI: SagaCont[] = [
  { cod: "101", denumire: "CAPITAL SOCIAL", tip: "P" as const },
  { cod: "1011", denumire: "CAPITAL SUBSCRIS NEVARSAT", tip: "P" as const },
  { cod: "1012", denumire: "CAPITAL SUBSCRIS VARSAT", tip: "P" as const },
  { cod: "1015", denumire: "PATRIMONIUL REGIEI", tip: "P" as const },
  { cod: "1016", denumire: "PATRIMONIUL PUBLIC", tip: "P" as const },
  { cod: "1017", denumire: "PATRIMONIUL PRIVAT", tip: "P" as const },
  { cod: "1018", denumire: "PATRIMONIUL INSTITUTELOR DE CERCETARE-DEZVOLTARE", tip: "P" as const },
  { cod: "103", denumire: "ALTE ELEMENTE DE CAPITALURI PROPRII", tip: "B" as const },
  { cod: "1031", denumire: "BENEFICII ALE ANGAJATILOR SUB FORMA DE CAPITALURI PROPRII", tip: "P" as const },
  { cod: "1033", denumire: "DIFERENTE DE CURS PT. INVESTITIA ÎNTR-O ENTITITATE STRAINA", tip: "B" as const },
  { cod: "1038", denumire: "ALTE ELEMENTE DE CAPITALURI PROPRII", tip: "B" as const },
  { cod: "104", denumire: "PRIME DE CAPITAL", tip: "P" as const },
  { cod: "1041", denumire: "PRIME DE EMISIUNE", tip: "P" as const },
  { cod: "1042", denumire: "PRIME DE FUZIUNE/DIVIZARE", tip: "P" as const },
  { cod: "1043", denumire: "PRIME DE APORT", tip: "P" as const },
  { cod: "1044", denumire: "PRIME DE CONVERSIE A OBLIGATIUNILOR IN ACTIUNI", tip: "P" as const },
  { cod: "105", denumire: "REZERVE  DIN REEVALUARE", tip: "P" as const },
  { cod: "106", denumire: "REZERVE", tip: "P" as const },
  { cod: "1061", denumire: "REZERVE LEGALE", tip: "P" as const },
  { cod: "1063", denumire: "REZERVE STATUTARE SAU CONTRACTUALE", tip: "P" as const },
  { cod: "1068", denumire: "ALTE REZERVE", tip: "P" as const },
  { cod: "107", denumire: "DIFERENTE DE CURS VALUTAR DIN CONVERSIE", tip: "B" as const },
  { cod: "108", denumire: "INTERESE CARE NU CONTROLEAZA", tip: "B" as const },
  { cod: "1081", denumire: "INTERESE CARE NU CONTROLEAZA REZULT. EXERCITIULUI FINANCIAR", tip: "B" as const },
  { cod: "1082", denumire: "INTERESE CARE NU CONTROLEAZA - ALTE CAPITALURI PROPRII", tip: "B" as const },
  { cod: "109", denumire: "ACTIUNI PROPRII", tip: "A" as const },
  { cod: "1091", denumire: "ACTIUNI PROPRII DETINUTE PE TERMEN SCURT", tip: "A" as const },
  { cod: "1092", denumire: "ACTIUNI PROPRII DETINUTE PE TERMEN LUNG", tip: "A" as const },
  { cod: "1095", denumire: "ACTIUNI DETINUTE DE SOCIETATEA ABSORBITA LA CEA ABSORBANTA", tip: "A" as const },
  { cod: "117", denumire: "REZULTATUL REPORTAT", tip: "B" as const },
  { cod: "1171", denumire: "REZULTATUL REPORTAT - PROFITUL NEREP./ PIREDERE NEACOP.", tip: "B" as const },
  { cod: "1172", denumire: "REZULTATUL REPORTAT DIN ADOPTAREA IAS", tip: "B" as const },
  { cod: "1173", denumire: "REZULTATUL REPORTAT DIN MODIFICARILE POLITICILOR COTABILE", tip: "B" as const },
  { cod: "1174", denumire: "REZULTATUL REPORTAT DIN CORECTAREA ERORILOR CONTAB.", tip: "B" as const },
  { cod: "1175", denumire: "REZULTATUL REPORTAT DIN SURPLUSUL DIN REZERVE DIN REEVALUARE", tip: "P" as const },
  { cod: "1176", denumire: "REZULTATUL REPORTAT PROVENIT DIN TRECEREA LA DIREC. IV", tip: "B" as const },
  { cod: "121", denumire: "PROFIT SI PIERDERE", tip: "B" as const },
  { cod: "129", denumire: "REPARTIZAREA PROFITULUI", tip: "A" as const },
  { cod: "141", denumire: "CASTIGURI LEGATE DE INSTRUMENTELE DE CAPITALURI PROPRII", tip: "P" as const },
  { cod: "1411", denumire: "CASTIGURI DIN VANZAREA INSTRUMENTELOR DE CAPITALURI PROPRII", tip: "P" as const },
  { cod: "1412", denumire: "CASTIGURI DIN ANULAREA INSTRUMENTELOR DE CAPITALURI PROPRII", tip: "P" as const },
  { cod: "149", denumire: "PIERDERI LEGATE DE OPERATII CU TITUL GRATUIT DE CAP. PROPRII", tip: "A" as const },
  { cod: "1491", denumire: "PIERDERI DIN VANZAREA INSTRUMENTELOR DE CAPITALURI PROPRII", tip: "A" as const },
  { cod: "1495", denumire: "PIERDERI DIN REORGANIZARI, ANULAREA TITLURILOR DETINUTE", tip: "A" as const },
  { cod: "1496", denumire: "PIERDERI DIN REORGANIZARI DE SOCIET PT. ACTIVUL NET NEGATIV", tip: "A" as const },
  { cod: "1498", denumire: "ALTE PIERDERI LEGATE DE INSTRUMENTELE DE CAPITALURI PROPRII", tip: "A" as const },
  { cod: "151", denumire: "PROVIZIOANE", tip: "P" as const },
  { cod: "1511", denumire: "PROVIZIOANE PENTRU LITIGII", tip: "P" as const },
  { cod: "1512", denumire: "PROVIZIOANE PENTRU GARANTII ACORDATE CLIENTILOR", tip: "P" as const },
  { cod: "1513", denumire: "PROVIZIOANE PENTRU DEZAFECTARE IMOBILIZARI CORPORALE", tip: "P" as const },
  { cod: "1514", denumire: "PROVIZIOANE PENTRU RESTRUCTURARE", tip: "P" as const },
  { cod: "1515", denumire: "PROVIZIOANE PENTRU PENSII SI OBLIGATII SIMILARE", tip: "P" as const },
  { cod: "1516", denumire: "PROVIZIOANE PENTRU IMPOZITE", tip: "P" as const },
  { cod: "1517", denumire: "PROVIZIOANE PENTRU TERMINAREA CONTRACTULUI DE MUNCA", tip: "P" as const },
  { cod: "1518", denumire: "ALTE PROVIZIOANE", tip: "P" as const },
  { cod: "161", denumire: "IMPR. DIN EMISIUNI DE OBLIGATIUNI", tip: "P" as const },
  { cod: "1614", denumire: "IMPR. EXTERNE DIN EMISIUNI DE OBLIG. GARANTATE DE STAT", tip: "P" as const },
  { cod: "1615", denumire: "IMPR. EXTERNE DIN EMISIUNI DE OBLIG. GARANTATE DE BANCI", tip: "P" as const },
  { cod: "1617", denumire: "IMPR. INTERNE DIN EMISIUNI DE OBLIG. GARANTATE DE STAT", tip: "P" as const },
  { cod: "1618", denumire: "ALTE IMPR. DIN EMISIUNI DE OBLIG.", tip: "P" as const },
  { cod: "162", denumire: "CREDITE BANCARE PE TERMEN LUNG", tip: "P" as const },
  { cod: "1621", denumire: "CREDITE BANCARE PE TERMEN LUNG", tip: "P" as const },
  { cod: "1622", denumire: "CREDITE BANCARE PE TERMEN LUNG NERABURSATE", tip: "P" as const },
  { cod: "1623", denumire: "CREDITE EXTERNE GUVERNAMENTALE", tip: "P" as const },
  { cod: "1624", denumire: "CREDITE EXTERNE GARANTATE DE STAT", tip: "P" as const },
  { cod: "1625", denumire: "CREDITE EXTERNE GARANTATE DE BANCI", tip: "P" as const },
  { cod: "1626", denumire: "CREDITE DE LA TREZORERIA STATULUI", tip: "P" as const },
  { cod: "1627", denumire: "CREDITE BANCARE INTERNE GARANTATE DE STAT", tip: "P" as const },
  { cod: "166", denumire: "DATORII CE PRIVESC IMOBILIZARILE FINANCIARE", tip: "P" as const },
  { cod: "1661", denumire: "DATORII FATA DE ENTITATILE AFILIATE", tip: "P" as const },
  { cod: "1663", denumire: "DATORII FATA DE ENTITATILE ASOCIATE / CONTROLATE IN COMUN", tip: "P" as const },
  { cod: "167", denumire: "ALTE IMPRUMUTURI SI DATORII ASIMILATE", tip: "P" as const },
  { cod: "168", denumire: "DOBANZI AFERENTE IMPRUMUTURILOR SI DATORII ASIMILATE", tip: "P" as const },
  { cod: "1681", denumire: "DOBANZI AFERENTE IMPRUMUTURILOR DIN OBLIGATIUNI", tip: "P" as const },
  { cod: "1682", denumire: "DOBANZI AFERENTE CREDITELOR BANCARE TERMEN LUNG", tip: "P" as const },
  { cod: "1685", denumire: "DOBANZI AFERENTE DATORIILOR FATA DE ENTITATILE AFILIATE", tip: "P" as const },
  { cod: "1686", denumire: "DOBANZI AFERENTE DATORIILOR FATA DE ENTITATILE ASOCIATE", tip: "P" as const },
  { cod: "1687", denumire: "DOBANZI AFERENTE ALTOR IMPRUMUTURI SI DATORII ASIMILATE", tip: "P" as const },
  { cod: "169", denumire: "PRIME PRIVIND RAMBURSAREA OBLIGATIUNILOR SI A ALTOR DATORII", tip: "A" as const },
  { cod: "1691", denumire: "PRIME PRIVIND RAMBURSAREA OBLIGATIUNILOR", tip: "A" as const },
  { cod: "1692", denumire: "PRIME PRIVIND RAMBURSAREA ALTOR DATORII", tip: "A" as const },
  { cod: "201", denumire: "CHELTUIELI DE CONSTITUIRE", tip: "A" as const },
  { cod: "203", denumire: "CHELTUIELI DE DEZVOLTARE", tip: "A" as const },
  { cod: "205", denumire: "CONCESIUNI, BREVETE, LICENTE, MARCI COMERCIALE", tip: "A" as const },
  { cod: "206", denumire: "ACTIVE NECROP. DE EXPLORARE SI EVALUARE RESURSE MINERALE", tip: "A" as const },
  { cod: "207", denumire: "FOND COMERCIAL", tip: "B" as const },
  { cod: "2071", denumire: "FOND COMERCIAL POZITIV", tip: "A" as const },
  { cod: "2075", denumire: "FOND COMERCIAL NEGATIV", tip: "P" as const },
  { cod: "208", denumire: "ALTE IMOBILIZARI NECORPORALE", tip: "A" as const },
  { cod: "211", denumire: "TERENURI,  AMENAJARI DE TERENURI", tip: "A" as const },
  { cod: "2111", denumire: "TERENURI", tip: "A" as const },
  { cod: "2112", denumire: "AMENAJARI DE TERENURI", tip: "A" as const },
  { cod: "212", denumire: "CONSTRUCTII", tip: "A" as const },
  { cod: "213", denumire: "INSTALATII TEHNICE SI MIJLOACE TRANSPORT", tip: "A" as const },
  { cod: "2131", denumire: "ECHIPAMENTE TEHNOLOGICE (MASINI,UTILAJE)", tip: "A" as const },
  { cod: "2132", denumire: "APARATE SI INSTALATII DE MASURA, CONTROL SI REGLARE", tip: "A" as const },
  { cod: "2133", denumire: "MIJLOACE DE TRANSPORT", tip: "A" as const },
  { cod: "214", denumire: "MOBILIER, APARATURA BIROTICA, ALTE ACTIVE CORPORALE", tip: "A" as const },
  { cod: "215", denumire: "INVESTITII IMOBILIARE", tip: "A" as const },
  { cod: "216", denumire: "ACTIVE CORPORALE DE EXPL. SI EVAL. A RESURSELOR MINERALE", tip: "A" as const },
  { cod: "217", denumire: "ACTIVE BIOLOGICE PRODUCTIVE", tip: "A" as const },
  { cod: "223", denumire: "INSTALATII TEHNICE, MIJLOACE DE TRANSPORT IN CURS DE APROV.", tip: "A" as const },
  { cod: "224", denumire: "MOBILIER, APARATURA BIROTICA IN CURS DEAPROVIZIONARE", tip: "A" as const },
  { cod: "227", denumire: "ACTIVE BIOLOGICE PRODUCTIVE IN CURS DE APROVIZIONARE", tip: "A" as const },
  { cod: "231", denumire: "IMOBILIZARI CORPORALE IN CURS DE EXECUTIE", tip: "A" as const },
  { cod: "235", denumire: "INVESTITII IMOBILIARE IN CURS DE EXECUTIE", tip: "A" as const },
  { cod: "261", denumire: "ACTIUNI DETINUTE LA ENTITATILE AFILIATE", tip: "A" as const },
  { cod: "262", denumire: "ACTIUNI DETINUTE LA ENTITATI ASOCIATE", tip: "A" as const },
  { cod: "263", denumire: "ACTIUNI DETINUTE LA ENTITATI CONTROLATE IN COMUN", tip: "A" as const },
  { cod: "264", denumire: "TITLURI PUSE ÎN ECHIVALENTA", tip: "A" as const },
  { cod: "265", denumire: "ALTE TITLURI IMOBILIZATE", tip: "A" as const },
  { cod: "266", denumire: "CERTIFICATE VERZI AMANATE", tip: "A" as const },
  { cod: "267", denumire: "CREANTE IMOBILIZATE", tip: "A" as const },
  { cod: "2671", denumire: "SUME DATORATE DE ENTITATILE AFILIATE", tip: "A" as const },
  { cod: "2672", denumire: "DOBANDA AF. SUMELOR DAT. DE ENTITATILE AFILIATE", tip: "A" as const },
  { cod: "2673", denumire: "CREANTE FATA DE ENTITATILE ASOCIATE / CONTROLATE IN COMUN", tip: "A" as const },
  { cod: "2674", denumire: "DOBANDA PT. CREANTE FATA DE ENTITATILE ASOCIATE", tip: "A" as const },
  { cod: "2675", denumire: "IMPRUMUTURI ACORDATE TERM. LUNG.", tip: "A" as const },
  { cod: "2676", denumire: "DOBANDA AFERENTA IMPRUMUTURILOR ACORDATE PE TERMEN LUNG", tip: "A" as const },
  { cod: "2677", denumire: "OBLIGATIUNI ACHIZITIONATE EMISE DE TERTI", tip: "A" as const },
  { cod: "2678", denumire: "ALTE CREANTE IMOBILIZATE", tip: "A" as const },
  { cod: "2679", denumire: "DOBANZI AFERENTE ALTOR CREANTE IMOB.", tip: "A" as const },
  { cod: "269", denumire: "VARSAMINTE DE EFECTUAT PT. IMOB. FINANCIARE", tip: "P" as const },
  { cod: "2691", denumire: "VARSAMINTE DE EFECTUAT PT. ACTIUNILE DETINUTE LA ENT. AFIL.", tip: "P" as const },
  { cod: "2692", denumire: "VARSAMINTE DE EFECTUAT PT. ACTIUNILE DETINUTE LA ENT. ASOC.", tip: "P" as const },
  { cod: "2693", denumire: "VARSAMINTE PT. ACTIUNILE DETINUTE LA ENT.CONTROLATE IN COMUN", tip: "P" as const },
  { cod: "2695", denumire: "VARSAMINTE DE EFECTUAT PENTRU ALTE IMOBILIZARI FINANCIARE", tip: "P" as const },
  { cod: "280", denumire: "AMORT. PRIVIND  IMOBILIZARILE NECORPORALE", tip: "P" as const },
  { cod: "2801", denumire: "AMORT. CHELTUIELILOR DE CONSTITUIRE", tip: "P" as const },
  { cod: "2803", denumire: "AMORT. CHELTUIELILOR DE DEZVOLTARE", tip: "P" as const },
  { cod: "2805", denumire: "AMORT. CONCESIUNI, BREVETE, LICENTE, MARCI COMERCIALE", tip: "P" as const },
  { cod: "2806", denumire: "AMORT. ACTIVELOR NECORP. DE EXPL. SI EVAL. A RES. MINERALE", tip: "P" as const },
  { cod: "2807", denumire: "AMORT.  FONDULUI COMERCIAL", tip: "P" as const },
  { cod: "2808", denumire: "AMORT. ALTOR  IMOB. NECORPORALE", tip: "P" as const },
  { cod: "281", denumire: "AMORT. PRIVIND  IMOBILIZARILE CORPORALE", tip: "P" as const },
  { cod: "2811", denumire: "AMORT. AMENAJARILOR DE TERENURI", tip: "P" as const },
  { cod: "2812", denumire: "AMORT. CONSTRUCTIILOR", tip: "P" as const },
  { cod: "2813", denumire: "AMORT. INSTALATIILOR, MIJ. DE TRANSPORT", tip: "P" as const },
  { cod: "2814", denumire: "AMORT. ALTOR IMOBILIZARI CORPORALE", tip: "P" as const },
  { cod: "2815", denumire: "AMORT. INVESTITIILOR IMOBILIARE", tip: "P" as const },
  { cod: "2816", denumire: "AMORT. ACTIVELOR CORP. DE EXPL. SI EVAL. A RESURSELOR MINER.", tip: "P" as const },
  { cod: "2817", denumire: "AMORT. ACTIVELOR BIOLOGICE PRODUCTIVE", tip: "P" as const },
  { cod: "290", denumire: "AJUSTARI - DEPRECIEREA IMOBILIZARILOR NECORPORALE", tip: "P" as const },
  { cod: "2903", denumire: "AJUSTARI - DEPRECIEREA CHELTUIELILOR DE DEZVOLTARE", tip: "P" as const },
  { cod: "2905", denumire: "AJUSTARI - DEPRECIEREA CONCESIUNILOR, BREVETELOR, LICENTE", tip: "P" as const },
  { cod: "2906", denumire: "AJUSTARI - DEPRECIEREA ACTIVELOR NECORPORALE DE EXPLORARE", tip: "P" as const },
  { cod: "2908", denumire: "AJUSTARI - DEPRECIEREA ALTOR IMOBILIZARI NECORPORALE", tip: "P" as const },
  { cod: "291", denumire: "AJUSTARI - DEPRECIEREA IMOBILIZARILOR CORPORALE", tip: "P" as const },
  { cod: "2911", denumire: "AJUSTARI - DEPRECIEREA TERENURILOR SI AMENAJARILOR", tip: "P" as const },
  { cod: "2912", denumire: "AJUSTARI - DEPRECIEREA CONSTRUCTIILOR", tip: "P" as const },
  { cod: "2913", denumire: "AJUSTARI - DEPRECIEREA INSTALATII TEHNICE,MIJ. TRANSP.", tip: "P" as const },
  { cod: "2914", denumire: "AJUSTARI - DEPRECIEREA ALTOR IMOBILIZARI CORPORALE", tip: "P" as const },
  { cod: "2915", denumire: "AJUSTARI - DEPRECIEREA INVESTI.IILOR IMOBILIARE", tip: "P" as const },
  { cod: "2916", denumire: "AJUSTARI - DEPRECIEREA ACTIVELOR CORPORALE DE EXPLORARE", tip: "P" as const },
  { cod: "2917", denumire: "AJUSTARI - DEPRECIEREA ACTIVELOR BIOLOGICE PRODUCTIVE", tip: "P" as const },
  { cod: "293", denumire: "AJUSTARI - DEPRECIEREA IMOBILIZARILOR IN CURS DE EXEC.", tip: "P" as const },
  { cod: "2931", denumire: "AJUSTARI - DEPR. IMOB. CORPORALE IN CURS DE EXECUTIE", tip: "P" as const },
  { cod: "2935", denumire: "AJUSTARI - DEPR. INVESTITIILOR IMOBILIARE IN CURS DE EXEC.", tip: "P" as const },
  { cod: "296", denumire: "AJUSTARI - PIERDEREA DE VALOARE A IMOBILIZARILOR FINANCIARE", tip: "P" as const },
  { cod: "2961", denumire: "AJUSTARI - PIERDEREA DE VALOARE A ACTIUNILOR LA ENTIT. AFIL.", tip: "P" as const },
  { cod: "2962", denumire: "AJUSTARI - PIERDEREA DE VALOARE A ACTIUNILOR LA ENTIT. ASOC.", tip: "P" as const },
  { cod: "2963", denumire: "AJUSTARI - PIERDEREA DE VALOARE A ALTOR TITLURI IMOBILIZATE", tip: "P" as const },
  { cod: "2964", denumire: "AJUSTARI - PIERDEREA DE VALOARE A SUMELOR DAT. DE ENTIT.AFIL", tip: "P" as const },
  { cod: "2965", denumire: "AJUSTARI - PIERDEREA DE VALOARE A CREANTELOR - INT. DE PART.", tip: "P" as const },
  { cod: "2966", denumire: "AJUSTARI - PIERDEREA DE VALOARE A A IMPRUM. PE TERMEN LUNG", tip: "P" as const },
  { cod: "2968", denumire: "AJUSTARI - PIERDEREA DE VALOARE A ALTOR CREANTE IMOBILIZATE", tip: "P" as const },
  { cod: "301", denumire: "MATERII PRIME", tip: "A" as const },
  { cod: "302", denumire: "MATERIALE CONSUMABILE", tip: "A" as const },
  { cod: "3021", denumire: "MATERIALE AUXILIARE", tip: "A" as const },
  { cod: "3022", denumire: "COMBUSTIBILI", tip: "A" as const },
  { cod: "3023", denumire: "MATERILAE PT. AMBALAT", tip: "A" as const },
  { cod: "3024", denumire: "PIESE DE SCHIMB", tip: "A" as const },
  { cod: "3025", denumire: "SEMINTE SI MATERIALE DE PLANTAT", tip: "A" as const },
  { cod: "3026", denumire: "FURAJE", tip: "A" as const },
  { cod: "3028", denumire: "ALTE MATERIALE CONSUMABILE", tip: "A" as const },
  { cod: "303", denumire: "MAT. DE NATURA OB. DE INVENTAR", tip: "A" as const },
  { cod: "308", denumire: "DIFERENTE DE PRET LA MATERII PRIME SI MATERIALE", tip: "B" as const },
  { cod: "321", denumire: "MATERII PRIME IN CURS DE APROVIZIONARE", tip: "A" as const },
  { cod: "322", denumire: "MATERIALE CONSUMABILE IN CURS DE APROVIZIONARE", tip: "A" as const },
  { cod: "323", denumire: "MATERIALE DE NATURA OBIECTELOR DE INVENTAR IN CURS DE APROV.", tip: "A" as const },
  { cod: "326", denumire: "ACTIVE BIOLOGICE DE NATURA STOCURILOR IN CURS DE APROVIZ.", tip: "A" as const },
  { cod: "327", denumire: "MARFURI IN CURS DE APROVIZIONARE", tip: "A" as const },
  { cod: "328", denumire: "AMBALAJE IN CURS DE APROVIZIONARE", tip: "A" as const },
  { cod: "331", denumire: "PRODUSE IN CURS DE EXECUTIE", tip: "A" as const },
  { cod: "332", denumire: "SERVICII IN CURS DE EXECUTIE", tip: "A" as const },
  { cod: "341", denumire: "SEMIFABRICATE", tip: "A" as const },
  { cod: "345", denumire: "PRODUSE FINITE", tip: "A" as const },
  { cod: "346", denumire: "PRODUSE REZIDUALE", tip: "A" as const },
  { cod: "347", denumire: "PRODUSE AGRICOLE", tip: "A" as const },
  { cod: "348", denumire: "DIFERENTE DE PRET LA PRODUSE", tip: "B" as const },
  { cod: "351", denumire: "MATERII SI MATERIALE LA TERTI", tip: "A" as const },
  { cod: "354", denumire: "PRODUSE AFLATE LA TERTI", tip: "A" as const },
  { cod: "356", denumire: "ACTIVE BIOLOGICE DE NATURA STOCURILOR AFLATE LA TERTI", tip: "A" as const },
  { cod: "357", denumire: "MARFURI AFLATE LA TERTI", tip: "A" as const },
  { cod: "358", denumire: "AMBALAJE AFLATE LA TERTI", tip: "A" as const },
  { cod: "361", denumire: "ACTIVE BIOLOGICE DE NATURA STOCURILOR", tip: "A" as const },
  { cod: "368", denumire: "DIFERENTE DE PRET LA ACTIVE BIOLOGICE DE NATURA STOCURILOR", tip: "B" as const },
  { cod: "371", denumire: "MARFURI", tip: "A" as const },
  { cod: "378", denumire: "DIFERENTE DE PRET LA MARFURI", tip: "B" as const },
  { cod: "381", denumire: "AMBALAJE", tip: "A" as const },
  { cod: "388", denumire: "DIFERENTE DE PRET LA AMBALAJE", tip: "B" as const },
  { cod: "391", denumire: "AJUSTARI - DEPRECIEREA MATERIILOR PRIME", tip: "P" as const },
  { cod: "392", denumire: "AJUSTARI - DEPRECIEREA MATERIALELOR", tip: "P" as const },
  { cod: "3921", denumire: "AJUSTARI - DEPRECIEREA MATERIALELOR CONSUMABILE", tip: "P" as const },
  { cod: "3922", denumire: "AJUSTARI - DEPRECIEREA OBIECTELOR DE INVENTAR", tip: "P" as const },
  { cod: "393", denumire: "AJUSTARI - DEPRECIEREA PRODUCTIEI IN CURS DE EXECUTIE", tip: "P" as const },
  { cod: "394", denumire: "AJUSTARI - DEPRECIEREA PRODUSELOR", tip: "P" as const },
  { cod: "3941", denumire: "AJUSTARI - DEPRECIEREA SEMIFABRICATELOR", tip: "P" as const },
  { cod: "3945", denumire: "AJUSTARI - DEPRECIEREA PRODUSELOR FINITE", tip: "P" as const },
  { cod: "3946", denumire: "AJUSTARI - DEPRECIEREA PRODUSELOR REZIDUALE", tip: "P" as const },
  { cod: "3947", denumire: "AJUSTARI - DEPRECIEREA PRODUSELOR AGRICOLE", tip: "P" as const },
  { cod: "395", denumire: "AJUSTARI - DEPRECIEREA STOCURILOR AFLATE LA TERTI", tip: "P" as const },
  { cod: "3951", denumire: "AJUSTARI - DEPRECIEREA MATERIALELOR AFLATE LA TERTI", tip: "P" as const },
  { cod: "3952", denumire: "AJUSTARI - DEPRECIEREA SEMIFABRICATELOR AFLATE LA TERTI", tip: "P" as const },
  { cod: "3953", denumire: "AJUSTARI - DEPRECIEREA PRODUSELOR FINITE AFLATE LA TERTI", tip: "P" as const },
  { cod: "3954", denumire: "AJUSTARI - DEPRECIEREA PRODUSELOR REZID. AFLATE LA TERTI", tip: "P" as const },
  { cod: "3955", denumire: "AJUSTARI PENTRU DEPRECIEREA PRODUSELOR AGRICOLE AFLATE", tip: "P" as const },
  { cod: "3956", denumire: "AJUSTARI - DEPRECIEREA ACTIVELOR BIOLOGICE AFLATE LA TERTI", tip: "P" as const },
  { cod: "3957", denumire: "AJUSTARI - DEPRECIEREA MARFURILOR AFLATE LA TERTI", tip: "P" as const },
  { cod: "3958", denumire: "AJUSTARI - DEPRECIEREA AMBALAJELOR AFLATE LA TERTI", tip: "P" as const },
  { cod: "396", denumire: "AJUSTARI - DEPRECIEREA ACTIVELOR BIOLOGICE", tip: "P" as const },
  { cod: "397", denumire: "AJUSTARI - DEPRECIEREA MARFURILOR", tip: "P" as const },
  { cod: "398", denumire: "AJUSTARI - DEPRECIEREA AMBALAJELOR", tip: "P" as const },
  { cod: "401", denumire: "FURNIZORI", tip: "P" as const },
  { cod: "403", denumire: "EFECTE DE PLATIT", tip: "P" as const },
  { cod: "404", denumire: "FURNIZORI DE IMOBILIZARI", tip: "P" as const },
  { cod: "405", denumire: "EFECTE DE PLATIT PENTRU IMOBILIZARI", tip: "P" as const },
  { cod: "408", denumire: "FURNIZORI - FACTURI NESOSITE", tip: "P" as const },
  { cod: "409", denumire: "FURNIZORI - DEBITORI", tip: "A" as const },
  { cod: "4091", denumire: "FURNIZORI — DEBITORI PT. CUMPARARI DE BUNURI (STOCURI)", tip: "A" as const },
  { cod: "4092", denumire: "FURNIZORI — DEBITORI PT. PRESTARI DE SERVICII", tip: "A" as const },
  { cod: "4093", denumire: "AVANSURI ACORDATE PENTRU IMOBILIZARI CORPORALE", tip: "A" as const },
  { cod: "4094", denumire: "AVANSURI ACORDATE PENTRU IMOBILIZARI NECORPORALE", tip: "A" as const },
  { cod: "411", denumire: "CLIENTI", tip: "A" as const },
  { cod: "4111", denumire: "CLIENTI", tip: "A" as const },
  { cod: "4118", denumire: "CLIENTI INCERTI SAU IN LITIGIU", tip: "A" as const },
  { cod: "413", denumire: "EFECTE DE PRIMIT DE LA CLIENTI", tip: "A" as const },
  { cod: "418", denumire: "CLIENTI - FACTURI DE INTOCMIT", tip: "A" as const },
  { cod: "419", denumire: "CLIENTI - CREDITORI", tip: "P" as const },
  { cod: "421", denumire: "PERSONAL - SALARII DATORATE", tip: "P" as const },
  { cod: "423", denumire: "PERSONAL - AJUTOARE MATERIALE DATORATE", tip: "P" as const },
  { cod: "424", denumire: "PRIME PRIVIND PARTICIPAREA  PERSONALULUI  LA PROFIT", tip: "P" as const },
  { cod: "425", denumire: "AVANSURI ACORDATE PERSONALULUI", tip: "A" as const },
  { cod: "426", denumire: "DREPTURI DE PERSONAL NERIDICATE", tip: "P" as const },
  { cod: "427", denumire: "RETINERI DIN SALARII DATORATE TERTILOR", tip: "P" as const },
  { cod: "428", denumire: "ALTE DATORII SI CREANTE IN LEGATURA CU PERSONALUL", tip: "B" as const },
  { cod: "4281", denumire: "ALTE DATORII IN LEGATURA CU PERSONALUL", tip: "P" as const },
  { cod: "4282", denumire: "ALTE CREANTE IN LEGATURA CU PERSONALUL", tip: "A" as const },
  { cod: "431", denumire: "ASIGURARI   SOCIALE", tip: "P" as const },
  { cod: "4311", denumire: "CONTRIBUTIA UNITATII LA ASIGURARILE SOCIALE", tip: "P" as const },
  { cod: "4312", denumire: "CONTRIBUTIA PERSONALULUI LA ASIGURARILE SOCIALE", tip: "P" as const },
  { cod: "4313", denumire: "CONTRIBUTIA ANGAJATORULUI - ASIGURARILE SOCIALE DE SANATATE", tip: "P" as const },
  { cod: "4314", denumire: "CONTRIBUTIA ANGAJATILOR - ASIGURARILE SOCIALE DE SANATATE", tip: "P" as const },
  { cod: "4315", denumire: "CONTR. DE ASIGURARI SOCIALE", tip: "P" as const },
  { cod: "4316", denumire: "CONTR. DE ASIGURARI SOCIALE DE SANATATE", tip: "P" as const },
  { cod: "4318", denumire: "ALTE CONTRIBUTII PENTRU ASIGURARILE SOCIALE DE SANATATE", tip: "P" as const },
  { cod: "436", denumire: "CONTR. ASIGURATORIE DE MUNCA", tip: "P" as const },
  { cod: "437", denumire: "AJUTOR  DE  SOMAJ", tip: "P" as const },
  { cod: "4371", denumire: "CONTRIBUTIA UNITATII LA FONDUL DE SOMAJ", tip: "P" as const },
  { cod: "4372", denumire: "CONTRIBUTIA PERSONALULUI LA FONDUL DE SOMAJ", tip: "P" as const },
  { cod: "438", denumire: "ALTE DATORII SI CREANTE SOCIALE", tip: "B" as const },
  { cod: "4381", denumire: "ALTE DATORII SOCIALE", tip: "P" as const },
  { cod: "4382", denumire: "ALTE CREANTE SOCIALE", tip: "A" as const },
  { cod: "441", denumire: "IMPOZITUL PE PROFIT SI ALTE IMPOZITE", tip: "B" as const },
  { cod: "4411", denumire: "IMPOZITUL PE PROFIT", tip: "P" as const },
  { cod: "4415", denumire: "IMPOZITUL SPECIFIC UNOR ACTIVITATI", tip: "P" as const },
  { cod: "4417", denumire: "IMPOZITUL PE PROFIT LA NIVELUL IMPOZITULUI MINIM PE CA", tip: "P" as const },
  { cod: "4418", denumire: "IMPOZITUL PE VENIT", tip: "P" as const },
  { cod: "442", denumire: "TAXA PE VALOAREA ADAUGATA", tip: "B" as const },
  { cod: "4423", denumire: "TVA DE PLATA", tip: "P" as const },
  { cod: "4424", denumire: "TVA DE RECUPERAT", tip: "A" as const },
  { cod: "4426", denumire: "TVA DEDUCTIBILA", tip: "A" as const },
  { cod: "4427", denumire: "TVA COLECTATA", tip: "P" as const },
  { cod: "4428", denumire: "TVA NEEXIGIBILA", tip: "B" as const },
  { cod: "4428.M", denumire: "TVA NEEXIGIBILA - MARFURI", tip: "B" as const },
  { cod: "4428.TI", denumire: "TVA NEEXIGIBILA - INCASARE", tip: "B" as const },
  { cod: "4428.TP", denumire: "TVA NEEXIGIBILA - PLATA", tip: "B" as const },
  { cod: "444", denumire: "IMPOZITUL PE VENITURI DE NATURA SALARIILOR", tip: "P" as const },
  { cod: "445", denumire: "SUBVENTII", tip: "A" as const },
  { cod: "4451", denumire: "SUBVENTII GUVERNAMENTALE", tip: "A" as const },
  { cod: "4452", denumire: "IMPRUMUTURI NERAMBURSABILE CU CARACTER DE SUBVENTII", tip: "A" as const },
  { cod: "4458", denumire: "ALTE SUME PRIMITE CU CARACTER DE SUBVENTII", tip: "A" as const },
  { cod: "446", denumire: "ALTE IMPOZITE, TAXE SI VARSAMINTE ASIMILATE", tip: "P" as const },
  { cod: "447", denumire: "FONDURI SPECIALE TAXE SI VARSAMINTE ASIMILATE", tip: "P" as const },
  { cod: "448", denumire: "ALTE DATORII SI CREANTE CU BUGETUL STAT", tip: "B" as const },
  { cod: "4481", denumire: "ALTE DATORII FATA DE BUGETUL STATULUI", tip: "P" as const },
  { cod: "4482", denumire: "ALTE CREANTE PRIVIND BUGETUL STATULUI", tip: "A" as const },
  { cod: "451", denumire: "DECONTARI INTRE ENTITATILE AFILIATE", tip: "B" as const },
  { cod: "4511", denumire: "DECONTARI INTRE ENTITATILE AFILIATE", tip: "B" as const },
  { cod: "4518", denumire: "DOBINZI AFERENTE DECONTARILOR INTRE ENTITATILE AFILIATE", tip: "B" as const },
  { cod: "453", denumire: "DECONTARI CU ENTITATILE ASOCIATE SI ENTITATILE CONTROLATE", tip: "B" as const },
  { cod: "4531", denumire: "DECONTARI CU ENTITATILE ASOCIATE SI ENTITATILE CONTROLATE", tip: "B" as const },
  { cod: "4538", denumire: "DOBANZI AFERENTE DECONTARILOR CU ENTITATILE ASOCIATE", tip: "B" as const },
  { cod: "455", denumire: "SUME DATORATE ACTIONARILOR/ASOCIATILOR", tip: "P" as const },
  { cod: "4551", denumire: "ACTIONARI/ASOCIATI - CONTURI CURENTE", tip: "P" as const },
  { cod: "4558", denumire: "ACTIONARI/ASOCIATI - DOBANZI LA CONTURI CURENTE", tip: "P" as const },
  { cod: "456", denumire: "DECONTARI CU ACTIONARI/ASOCIATI PRIVIND CAPITALUL", tip: "B" as const },
  { cod: "457", denumire: "DIVIDENDE DE PLATIT", tip: "P" as const },
  { cod: "458", denumire: "DECONTARI DIN OPERATIUNI IN PARTICIPATIE", tip: "B" as const },
  { cod: "4581", denumire: "DECONTARI DIN OPERATIUNI IN PARTICIPATIE - PASIV", tip: "P" as const },
  { cod: "4582", denumire: "DECONTARI DIN OPERATIUNI IN PARTICIPATIE - ACTIV", tip: "A" as const },
  { cod: "461", denumire: "DEBITORI DIVERSI", tip: "A" as const },
  { cod: "461.SGR", denumire: "AMBALAJE SGR", tip: "A" as const },
  { cod: "462", denumire: "CREDITORI DIVERSI", tip: "P" as const },
  { cod: "463", denumire: "CREANTE REPREZ. DIVIDENDE REPARTIZATE IN CURSUL EXERCITIULUI", tip: "A" as const },
  { cod: "466", denumire: "DECONTARI DIN OPERATIUNI DE FIDUCIE", tip: "B" as const },
  { cod: "4661", denumire: "DATORII DIN OPERATIUNI DE FIDUCIE", tip: "A" as const },
  { cod: "4662", denumire: "CREANTE DIN OPERATIUNI DE FIDUCIE", tip: "P" as const },
  { cod: "467", denumire: "DATORII AFERENTE DISTRIBUIRILOR INTERIMARE DE DIVIDENDE", tip: "P" as const },
  { cod: "471", denumire: "CHELTUIELI INREGISTRATE IN AVANS", tip: "A" as const },
  { cod: "472", denumire: "VENITURI INREGISTRATE IN AVANS", tip: "P" as const },
  { cod: "473", denumire: "DECONTARI DIN OPERATIUNI IN CURS DE CLARIFICARE", tip: "B" as const },
  { cod: "475", denumire: "SUBVENTII PENTRU INVESTITII", tip: "P" as const },
  { cod: "4751", denumire: "SUBVENTII GUVERNAMENTALE PENTRU INVESTITII", tip: "P" as const },
  { cod: "4752", denumire: "IMPRUMUTURI NERAMB. CU CARACTER DE SUBVENTII PT. INVESTITII", tip: "P" as const },
  { cod: "4753", denumire: "DONATII PENTRU INVESTITII", tip: "P" as const },
  { cod: "4754", denumire: "PLUSURI DE INVENTAR DE NATURA IMOBILIZARILOR", tip: "P" as const },
  { cod: "4758", denumire: "ALTE SUME PRIMITE CU CARACTER DE SUBVENTII PENTRU INVESTITII", tip: "P" as const },
  { cod: "478", denumire: "VENITURI IN AVANS AFERENTE ACTIVELOR PRIMITE DE LA CLIENTI", tip: "P" as const },
  { cod: "481", denumire: "DECONTARI UNITATE SI SUBUNITATI", tip: "B" as const },
  { cod: "482", denumire: "DECONTARI INTRE SUBUNITATI", tip: "B" as const },
  { cod: "490", denumire: "AJUSTARI PT. DEPR. CREANTELOR AF. AVANSURILOR PT. FURNIZORI", tip: "P" as const },
  { cod: "4901", denumire: "AJUSTARI PT. DEPR. CREANTELOR AF. STOCURILOR", tip: "P" as const },
  { cod: "4902", denumire: "AJUSTARI PT. DEPR. CREANTELOR AF. SERVICIILOR", tip: "P" as const },
  { cod: "4903", denumire: "AJUSTARI PT. DEPR. CREANTELOR AF. IMOBILIZARILOR CORPORALE", tip: "P" as const },
  { cod: "4904", denumire: "AJUSTARI PT. DEPR. CREANTELOR AF. IMOBILIZARILOR NECORPORALE", tip: "P" as const },
  { cod: "491", denumire: "AJUSTARI - DEPRECIEREA CREANTELOR - CLIENTI", tip: "P" as const },
  { cod: "495", denumire: "AJUSTARI - DEPRECIEREA CREANTELOR - DECONTARI ASOCIATI", tip: "P" as const },
  { cod: "496", denumire: "AJUSTARI - DEPRECIEREA CREANTELOR - DEBITORI DIVERSI", tip: "P" as const },
  { cod: "501", denumire: "ACTIUNI DETINUTE LA ENTITATILE AFILIATE", tip: "A" as const },
  { cod: "505", denumire: "OBLIGATIUNI EMISE SI RASCUMPARATE", tip: "A" as const },
  { cod: "506", denumire: "OBLIGATIUNI", tip: "A" as const },
  { cod: "507", denumire: "CERTIFICATE VERZI PRIMITE", tip: "A" as const },
  { cod: "508", denumire: "ALTE INVESTITII PE TERMEN SCURT SI CREANTE ASIMILATE", tip: "A" as const },
  { cod: "5081", denumire: "ALTE TITLURI DE PLASAMENT", tip: "A" as const },
  { cod: "5088", denumire: "DOBANZI LA OBLIGATIUNI SI TITLURI PLASAMENT", tip: "A" as const },
  { cod: "509", denumire: "VARSAMINTE DE EFECTUAT PENTRU INVESTITIILE PE TERMEN SCURT", tip: "P" as const },
  { cod: "5091", denumire: "VARSAMINTE DE EFECTUAT- ACTIUNILE DETINUTE LA ENTITATI AFIL.", tip: "P" as const },
  { cod: "5092", denumire: "VARSAMINTE DE EFECTUAT - ALTE INVESTITII PE TERMEN SCURT", tip: "P" as const },
  { cod: "511", denumire: "VALORI DE INCASAT", tip: "A" as const },
  { cod: "5112", denumire: "CECURI DE INCASAT", tip: "A" as const },
  { cod: "5113", denumire: "EFECTE DE INCASAT", tip: "A" as const },
  { cod: "5114", denumire: "EFECTE REMISE SPRE SCONTARE", tip: "A" as const },
  { cod: "512", denumire: "CONTURI CURENTE LA BANCI", tip: "B" as const },
  { cod: "5121", denumire: "CONTURI LA BANCA IN LEI", tip: "B" as const },
  { cod: "5124", denumire: "CONTURI LA BANCA IN VALUTA", tip: "B" as const },
  { cod: "5125", denumire: "SUME IN CURS DE DECONTARE", tip: "A" as const },
  { cod: "5126", denumire: "CONTURI LA BANCI ÎN LEI TVA DEFALCAT", tip: "B" as const },
  { cod: "5127", denumire: "CONTURI LA BANCI ÎN VALUTA TVA DEFALCAT", tip: "B" as const },
  { cod: "518", denumire: "DOBANZI", tip: "B" as const },
  { cod: "5186", denumire: "DOBANZI DE PLATIT", tip: "P" as const },
  { cod: "5187", denumire: "DOBANZI DE INCASAT", tip: "A" as const },
  { cod: "519", denumire: "CREDITE BANC.TERMEN SCURT", tip: "P" as const },
  { cod: "5191", denumire: "CREDITE BANCARE PE TERMEN SCURT", tip: "P" as const },
  { cod: "5192", denumire: "CREDITE BANCARE PE TERMEN SCURT NERAMBURSATE LA SCADENTA", tip: "P" as const },
  { cod: "5193", denumire: "CREDITE EXTERNE GUVERNAMENTALE", tip: "P" as const },
  { cod: "5194", denumire: "CREDITE EXTERNE GARANTATE DE STAT", tip: "P" as const },
  { cod: "5195", denumire: "CREDITE EXTERNE GARANTATE DE BANCI", tip: "P" as const },
  { cod: "5196", denumire: "CREDITE DE LA TREZORERIE STATULUI", tip: "P" as const },
  { cod: "5197", denumire: "CREDITE INTERNE GARANTATE STAT", tip: "P" as const },
  { cod: "5198", denumire: "DOBANZI AFERENTE CREDITELOR BANCARE PE TERMEN SCURT", tip: "P" as const },
  { cod: "531", denumire: "CASA", tip: "A" as const },
  { cod: "5311", denumire: "CASA IN LEI", tip: "A" as const },
  { cod: "5314", denumire: "CASA IN VALUTA", tip: "A" as const },
  { cod: "532", denumire: "ALTE VALORI", tip: "A" as const },
  { cod: "5321", denumire: "TIMBRE FISCALE SI POSTALE", tip: "A" as const },
  { cod: "5322", denumire: "BILETE DE TRATAMENT SI ODIHNA", tip: "A" as const },
  { cod: "5323", denumire: "TICHETE SI BILETE DE CALATORIE", tip: "A" as const },
  { cod: "5328", denumire: "ALTE VALORI", tip: "A" as const },
  { cod: "541", denumire: "ACREDITIVE", tip: "A" as const },
  { cod: "5411", denumire: "ACREDITIVE IN LEI", tip: "A" as const },
  { cod: "5414", denumire: "ACREDITIVE IN VALUTA", tip: "A" as const },
  { cod: "542", denumire: "AVANSURI DE TREZORERIE", tip: "A" as const },
  { cod: "581", denumire: "VIRAMENTE INTERNE", tip: "B" as const },
  { cod: "591", denumire: "AJUSTARI - DEPR. ACTIUNILOR DETINUTE LA ENTITATILE AFILIATE", tip: "P" as const },
  { cod: "595", denumire: "AJUSTARI - DEPR. OBLIGATIUNILOR EMISE SI RASCUMPARATE", tip: "P" as const },
  { cod: "596", denumire: "AJUSTARI - DEPR. OBLIGATIUNILOR", tip: "P" as const },
  { cod: "598", denumire: "AJUSTARI - DEPR. ALTOR INVESTITII PE TERMEN SCUT", tip: "P" as const },
  { cod: "601", denumire: "CHELT. CU MATERIILE PRIME", tip: "A" as const },
  { cod: "602", denumire: "CHELT.CU MATERIALELE CONSUMABILE", tip: "A" as const },
  { cod: "6021", denumire: "CHELT. CU MATERIALE AUXILIARE", tip: "A" as const },
  { cod: "6022", denumire: "CHELT. PRIVIND COMBUSTIBILUL", tip: "A" as const },
  { cod: "6023", denumire: "CHELT. PRIVIND AMBALAJUL", tip: "A" as const },
  { cod: "6024", denumire: "CHELT. CU PIESELE DE SCHIMB", tip: "A" as const },
  { cod: "6025", denumire: "CHELT. CU SEMINTE SI MAT. PLANT.", tip: "A" as const },
  { cod: "6026", denumire: "CHELT. CU FURAJELE", tip: "A" as const },
  { cod: "6028", denumire: "CHELT.CU ALTE MAT.CONSUMABILE", tip: "A" as const },
  { cod: "603", denumire: "CHELT. CU OBIECTE DE INVENTAR", tip: "A" as const },
  { cod: "604", denumire: "CHELT. CU MAT.NESTOCATE", tip: "A" as const },
  { cod: "605", denumire: "CHELT. CU ENERGIA SI APA", tip: "A" as const },
  { cod: "6051", denumire: "CHELT. PRIVIND CONSUMUL DE ENERGIE", tip: "A" as const },
  { cod: "6052", denumire: "CHELT. PRIVIND CONSUMUL DE APA", tip: "A" as const },
  { cod: "6053", denumire: "CHELT. PRIVIND CONSUMUL DE GAZE NATURALE", tip: "A" as const },
  { cod: "6058", denumire: "CHELT. CU ALTE UTILITATI", tip: "A" as const },
  { cod: "606", denumire: "CHELT. CU PRIVIND ACTIVELE BIOLOGICE DE NATURA STOCURILOR", tip: "A" as const },
  { cod: "607", denumire: "CHELT. PRIVIND MARFURILE", tip: "A" as const },
  { cod: "608", denumire: "CHELT. PRIVIND AMBALAJELE", tip: "A" as const },
  { cod: "609", denumire: "REDUCERI COMERCIALE PRIMITE", tip: "P" as const },
  { cod: "611", denumire: "CHELT. CU INTRETINEREA SI REPARATIILE", tip: "A" as const },
  { cod: "612", denumire: "CHELT. CU REDEVENTE, LOCATIILE DE GESTIUNE SI CHIRIILE", tip: "A" as const },
  { cod: "6121", denumire: "CHELTUIELI CU REDEVENTELE", tip: "A" as const },
  { cod: "6122", denumire: "CHELTUIELI CU LOCATIILE DE GESTIUNE", tip: "A" as const },
  { cod: "6123", denumire: "CHELTUIELI CU CHIRIILE", tip: "A" as const },
  { cod: "613", denumire: "CHELT. CU PRIME DE ASIGURARE", tip: "A" as const },
  { cod: "614", denumire: "CHELT. CU STUDII SI CERCETARI", tip: "A" as const },
  { cod: "615", denumire: "CHELT. CU PREGATIREA PERSONALULUI", tip: "A" as const },
  { cod: "616", denumire: "CHELTUIELI AFERENTE DREPTURILOR DE PROPRIETATE INTELECTUALA", tip: "A" as const },
  { cod: "617", denumire: "CHELTUIELI DE MANAGEMENT", tip: "A" as const },
  { cod: "618", denumire: "CHELTUIELI DE CONSULTANTA", tip: "A" as const },
  { cod: "621", denumire: "CHELT. CU COLABORATORII", tip: "A" as const },
  { cod: "622", denumire: "CHELT. CU COMISIOANE SI ONORARIILE", tip: "A" as const },
  { cod: "623", denumire: "CHELT. DE PROTOCOL, RECLAMA SI PUBLICITATE", tip: "A" as const },
  { cod: "6231", denumire: "CHELTUIELI DE PROTOCOL", tip: "A" as const },
  { cod: "6232", denumire: "CHELTUIELI DE RECLAMA SI PUBLICITATE", tip: "A" as const },
  { cod: "624", denumire: "CHELT. CU TRANSPORTUL DE BUNURI SI PERSONAL", tip: "A" as const },
  { cod: "625", denumire: "CHELT. CU DEPLASARI, DETASARI SI TRANSFERARI", tip: "A" as const },
  { cod: "626", denumire: "CHELT. POSTALE SI TAXE DE TELECOMUNICATII", tip: "A" as const },
  { cod: "627", denumire: "CHELT. CU SERV.BANCARE SI ASIMILATE", tip: "A" as const },
  { cod: "628", denumire: "ALTE CHELT. CU SERVICIILE EXECUTATE DE TERTI", tip: "A" as const },
  { cod: "635", denumire: "CHELT. CU ALTE IMPOZITE, TAXE SI VARSAMINTE ASIMILATE", tip: "A" as const },
  { cod: "641", denumire: "CHELT. CU SALARIILE PERSONALULUI", tip: "A" as const },
  { cod: "642", denumire: "CHELT. CU TICHETELE DE MASA SI AVANTAJELE IN NATURA ACORDATE", tip: "A" as const },
  { cod: "6421", denumire: "CHELT. CU AVANTAJELE IN NATURA ACORDATE SALARIATILOR", tip: "A" as const },
  { cod: "6422", denumire: "CHELT. CU TICHETELE DE MASA ACORDATE SALARIATILOR", tip: "A" as const },
  { cod: "643", denumire: "CHELT. CU REMUNERAREA IN INSTRUMENTE DE CAPITALURI PROPRII", tip: "A" as const },
  { cod: "644", denumire: "CHELT. CU PRIMELE REPREZENTAND PARTICIPAREA LA PROFIT", tip: "A" as const },
  { cod: "645", denumire: "CHELT. PRIVIND ASIGURARILE SI PROTECTIA SOCIALA", tip: "A" as const },
  { cod: "6451", denumire: "CHELT. PRIVIND CONTRIBUTIA UNITATII LA ASIGURARILE SOCIALE", tip: "A" as const },
  { cod: "6452", denumire: "CHELT. PRIVIND CONTRIBUTIA UNITATII PENTRU AJUTORUL DE SOMAJ", tip: "A" as const },
  { cod: "6453", denumire: "CHELT. PRIVIND CONRIB. UNITATII LA ASIG. SOCIALE DE SANATATE", tip: "A" as const },
  { cod: "6455", denumire: "CHELT. PRIVIND CONTRIBUTIA UNITATII LA ASIGURARILE DE VIATA", tip: "A" as const },
  { cod: "6456", denumire: "CONTRIB. UNITATII LA FONDURILE DE PENSII FACULTATIVE", tip: "A" as const },
  { cod: "6457", denumire: "CONTRIB. UNITATII LA PRIMELE DE ASIG. VOLUNTARA DE SANATATE", tip: "A" as const },
  { cod: "6458", denumire: "ALTE CHELT. PRIVIND ASIGURARILE SI PROTECTIA SOCIALA", tip: "A" as const },
  { cod: "646", denumire: "CHELT. CU CONTR. ASIGURATORIE DE MUNCA", tip: "A" as const },
  { cod: "6461", denumire: "CHELT. CU CONTRIB. ASIGURATORIE PT. MUNCA A SALARIATILOR", tip: "A" as const },
  { cod: "6462", denumire: "CHELT. CU CONTRIB. ASIGURATORIE PT. MUNCA A ALTOR PERSOANE", tip: "A" as const },
  { cod: "651", denumire: "CHELTUIELI DIN OPERATIUNI DE FIDUCIE", tip: "A" as const },
  { cod: "6511", denumire: "CHELTUIELI OCAZIONATE DE CONSTITUIREA FIDUCIEI", tip: "A" as const },
  { cod: "6512", denumire: "CHELTUIELI DIN DERULAREA OPERATIUNILOR DE FIDUCIE", tip: "A" as const },
  { cod: "6513", denumire: "CHELTUIELI DIN LICHIDAREA OPERATIUNILOR DE FIDUCIE", tip: "A" as const },
  { cod: "652", denumire: "CHELT. CU PROTECTIA MEDIULUI INCONJURATOR", tip: "A" as const },
  { cod: "654", denumire: "PIERDERI DIN CREANTE SI DEBITORI DIVERSI", tip: "A" as const },
  { cod: "655", denumire: "CHELT. DIN REEVALUAREA IMOBILIZARILOR", tip: "A" as const },
  { cod: "658", denumire: "ALTE CHELTUIELI DE EXPLOATARE", tip: "A" as const },
  { cod: "6581", denumire: "DESPAGUBIRI, AMENZI SI PENALITATI", tip: "A" as const },
  { cod: "6582", denumire: "DONATII ACORDATE", tip: "A" as const },
  { cod: "6583", denumire: "CHELT. ACTIVELE CEDATE SI ALTE OPERATIUNI DE CAPITAL", tip: "A" as const },
  { cod: "6584", denumire: "CHELT. CU SUMELE SAU BUNURILE ACORDATE CA SPONSORIZARI", tip: "A" as const },
  { cod: "6586", denumire: "CHELT. DIN TRANSFERURI ÎN BAZA UNOR ACTE NORMATIVE SPECIALE", tip: "A" as const },
  { cod: "6587", denumire: "CHELT. PRIVIND CALAMITATILE SI ALTE EVENIMENTE SIMILARE", tip: "A" as const },
  { cod: "6588", denumire: "ALTE CHELTUIELI DE EXPLOATARE", tip: "A" as const },
  { cod: "663", denumire: "PIERDERI DIN CREANTE LEGATE DE PARTICIPATII", tip: "A" as const },
  { cod: "664", denumire: "CHELT. CU INVESTITIILE FINANCIARE CEDATE", tip: "A" as const },
  { cod: "6641", denumire: "CHELT. CU IMOBOBILIZARILE FINANCIARE CEDATE", tip: "A" as const },
  { cod: "6642", denumire: "PIERDERI DIN INVESTITIILE PE TERMEN SCURT CEDATE", tip: "A" as const },
  { cod: "665", denumire: "CHELT. DIN DIFERENTE DE CURS VALUTAR", tip: "A" as const },
  { cod: "6651", denumire: "DIFERENTE NEFAVORABILE DE CURS VALUTAR", tip: "A" as const },
  { cod: "6652", denumire: "DIFERENTE DE CURS DIN INVESTITIA INTR-O ENTITATE STRAINA", tip: "A" as const },
  { cod: "666", denumire: "CHELT. PRIVIND DOBANZILE", tip: "A" as const },
  { cod: "667", denumire: "CHELT. CU SCONTURILE ACORDATE", tip: "A" as const },
  { cod: "668", denumire: "ALTE CHELTUIELI FINANCIARE", tip: "A" as const },
  { cod: "681", denumire: "CHELT. DE EXPLOATARE CU AMORTIZAREA SI PROVIZIOANLE", tip: "A" as const },
  { cod: "6811", denumire: "CHELT. DE EXPLOATARE CU AMORTIZAREA IMOBILIZARILOR", tip: "A" as const },
  { cod: "6812", denumire: "CHELT. DE EXPLOATARE CU PROVIZIOANLE", tip: "A" as const },
  { cod: "6813", denumire: "CHELT.  CU AJUSTARILE PT. DEPREC IMOBILIZARILOR", tip: "A" as const },
  { cod: "6814", denumire: "CHELT.  CU AJUSTARILE PT. DEPREC. ACTIVE CIRCULANTE", tip: "A" as const },
  { cod: "6817", denumire: "CHELT.  CU AJUSTARILE PT. DEPREC. FONDULUI COMERCIAL", tip: "A" as const },
  { cod: "6818", denumire: "CHELT. DIN DEPR. CREANTELOR AF. AVANSURILOR PT. FURNIZORI", tip: "A" as const },
  { cod: "686", denumire: "CHELT. FINANCIARE CU AMORTIZAREA SI PROVIZIOANELE", tip: "A" as const },
  { cod: "6861", denumire: "CHELT. PRIVIND ACTUALIZAREA PROVIZIOANELOR", tip: "A" as const },
  { cod: "6863", denumire: "CHELT. CU PROV. PT. DEPRECIEREA IMOBILIZARILOR FINANCIARE", tip: "A" as const },
  { cod: "6864", denumire: "CHELT. FIN. CU AJUSTARILE PT. PIERDEREA DE VAL. A ACT. CIRC.", tip: "A" as const },
  { cod: "6865", denumire: "CH. CU AMORTIZAREA DIFERENTELOR AFERENTE TITLURILOR DE STAT", tip: "A" as const },
  { cod: "6868", denumire: "CHELT. AMORT. PRIMELOR DE RAMBURSARE A OBLIGATIUNILOR", tip: "A" as const },
  { cod: "691", denumire: "CHELT. CU IMPOZITUL PE PROFIT", tip: "A" as const },
  { cod: "694", denumire: "CHELT. CU IMP. PE PROFIT REZULTAT DIN DECONTARILE ÎN GRUP", tip: "A" as const },
  { cod: "695", denumire: "CHELTUIELI CU IMPOZITUL SPECIFIC UNOR ACTIVITATI", tip: "A" as const },
  { cod: "697", denumire: "CHLT. CU IMP. PE PROFIT LA NIVELUL IMPOZITULUI MINIM PE CA", tip: "A" as const },
  { cod: "698", denumire: "CHELT. CU IMPOZITUL PE VENIT SI CU ALTE IMPOZITE", tip: "A" as const },
  { cod: "701", denumire: "VEN. DIN VANZAREA PROD. FINITE, PROD. AGRICOLE", tip: "P" as const },
  { cod: "7015", denumire: "VEN. DIN VANZAREA PROD. FINITE", tip: "P" as const },
  { cod: "7017", denumire: "VEN. DIN VANZAREA PROD. AGRICOLE", tip: "P" as const },
  { cod: "7018", denumire: "VEN. DIN VANZAREA ACTIVELOR BIOLOGICE DE NATURA STOCURILOR", tip: "P" as const },
  { cod: "702", denumire: "VEN. DIN VANZAREA SEMIFABRICATELOR", tip: "P" as const },
  { cod: "703", denumire: "VEN. DIN VANZAREA PRODUSELOR REZIDUALE", tip: "P" as const },
  { cod: "704", denumire: "VEN. DIN SERVICII PRESTATE", tip: "P" as const },
  { cod: "705", denumire: "VEN. DIN STUDII SI CERCETARI", tip: "P" as const },
  { cod: "706", denumire: "VEN. DIN REDEVENTE SI CHIRII", tip: "P" as const },
  { cod: "707", denumire: "VEN. DIN VANZARI DE MARFURI", tip: "P" as const },
  { cod: "708", denumire: "VEN. DIN ACTIVITATI DIVERSE", tip: "P" as const },
  { cod: "709", denumire: "REDUCERI COMERCIALE ACORDATE", tip: "A" as const },
  { cod: "711", denumire: "VARIATIA STOCURILOR", tip: "B" as const },
  { cod: "712", denumire: "VEN. AFERENTE COSTURILOR SERVICIILOR IN CURS DE EXECUTIE", tip: "P" as const },
  { cod: "721", denumire: "VEN. DIN PROD. DE IMOBILIZARI NECORPORALE", tip: "P" as const },
  { cod: "722", denumire: "VEN. DIN PROD. DE IMOBILIZARI CORPORALE", tip: "P" as const },
  { cod: "725", denumire: "VEN. DIN PROD. DE INVESTITII IMOBILIARE", tip: "P" as const },
  { cod: "741", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE", tip: "P" as const },
  { cod: "7411", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE AFERENTE C.A.", tip: "P" as const },
  { cod: "7412", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE PT. MATERII PRIME SI", tip: "P" as const },
  { cod: "7413", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE PT. ALTE CHELTUIELI", tip: "P" as const },
  { cod: "7414", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE PT. PLATA PERSONALUL", tip: "P" as const },
  { cod: "7415", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE PT. ASIG. SI PROTECTIE SOC.", tip: "P" as const },
  { cod: "7416", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE PT. ALTE CHELTUIELI DE EXP.", tip: "P" as const },
  { cod: "7417", denumire: "VEN. DIN SUBVENTII DE EXPL. IN CAZ DE CALAMITATI", tip: "P" as const },
  { cod: "7418", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE PT. DOBANDA DATORATA", tip: "P" as const },
  { cod: "7419", denumire: "VEN. DIN SUBVENTII DE EXPLOATARE AFERENTE ALTOR VENITURI", tip: "P" as const },
  { cod: "751", denumire: "VENITURI DIN OPERATIUNI DE FIDUCIE", tip: "P" as const },
  { cod: "7511", denumire: "VENITURI OCAZIONATE DE CONSTITUIREA FIDUCIEI", tip: "P" as const },
  { cod: "7512", denumire: "VENITURI DIN DERULAREA OPERATIUNILOR DE FIDUCIE", tip: "P" as const },
  { cod: "7513", denumire: "VENITURI DIN LICHIDAREA OPERATIUNILOR DE FIDUCIE", tip: "P" as const },
  { cod: "754", denumire: "VEN. DIN CREANTE REACTIVATE SI DEBITORI DIVERSI", tip: "P" as const },
  { cod: "755", denumire: "VEN. DIN REEVALUAREA IMOBILIZARILOR", tip: "P" as const },
  { cod: "758", denumire: "ALTE VENITURI DIN EXPLOATARE", tip: "P" as const },
  { cod: "7581", denumire: "VEN. DIN DESPAGUBIRI, AMENZI SI PENALITATI", tip: "P" as const },
  { cod: "7582", denumire: "VEN. DIN DONATII,SUBVENTII PRIMITE", tip: "P" as const },
  { cod: "7583", denumire: "VEN. DIN CEDAREA ACTIVELOR", tip: "P" as const },
  { cod: "7584", denumire: "VEN. DIN SUBVENTII PT. INVESTITII", tip: "P" as const },
  { cod: "7586", denumire: "VEN. DIN TRANSFERURI ÎN BAZA UNOR ACTE NORMATIVE SPECIALE", tip: "P" as const },
  { cod: "7588", denumire: "ALTE VENITURI DIN EXPLOATARE", tip: "P" as const },
  { cod: "761", denumire: "VEN. DIN IMOBILIZARI FINANCIARE", tip: "P" as const },
  { cod: "7611", denumire: "VEN. DIN ACTIUNI DETINUTE LA ENTITATI AFILIATE", tip: "P" as const },
  { cod: "7612", denumire: "VEN. DIN ACTIUNI DETINUTE LA ENTITATI ASOCIATE", tip: "P" as const },
  { cod: "7613", denumire: "VEN. DIN ACTIUNI DETINUTE LA ENTITATI CONTROLATE IN COMUN", tip: "P" as const },
  { cod: "7615", denumire: "VEN. DIN ALTE IMOBILIZARI FINANCIARE", tip: "P" as const },
  { cod: "762", denumire: "VEN. DIN INVEST. FIN. PE TERMEN SCURT", tip: "P" as const },
  { cod: "764", denumire: "VEN. DIN INVESTITII FINANCIARE CEDATE", tip: "P" as const },
  { cod: "7641", denumire: "VEN. DIN IMOBILIZARI FINANCIARE CEDATE", tip: "P" as const },
  { cod: "7642", denumire: "CASTIGURI DIN INVEST FINANCIARE PE TERMEN SCURT", tip: "P" as const },
  { cod: "765", denumire: "VEN. DIN DIFERENTE DE CURS VALUTAR", tip: "P" as const },
  { cod: "7651", denumire: "VEN. DIN DIFERENTE FAVORABILE DE CURS VALUTAR", tip: "P" as const },
  { cod: "7652", denumire: "DIFERENTE DE CURS DIN INVESTITIA INTR-O ENTITATE STRAINA", tip: "P" as const },
  { cod: "766", denumire: "VEN. DIN DOBINZI", tip: "P" as const },
  { cod: "767", denumire: "VEN. DIN SCONTURI OBTINUTE", tip: "P" as const },
  { cod: "768", denumire: "ALTE VEN. FINANCIARE", tip: "P" as const },
  { cod: "781", denumire: "VEN. PROV. PT. ACTIVIVITATEA DE EXPLOATARE", tip: "P" as const },
  { cod: "7812", denumire: "VEN. DIN PROVIZIOANE", tip: "P" as const },
  { cod: "7813", denumire: "VEN. DIN AJUSTARI PENTRU DEPR. IMOBILIZARILOR", tip: "P" as const },
  { cod: "7814", denumire: "VEN. DIN AJUSTARI PT. DEPR. ACTIVELOR CIRCCULANTE", tip: "P" as const },
  { cod: "7815", denumire: "VEN. DIN FONDUL COMERCIAL NEGATIV", tip: "P" as const },
  { cod: "7818", denumire: "VEN. DIN DEPR. CREANTELOR AF. AVANSURILOR PT. FURNIZORI", tip: "P" as const },
  { cod: "786", denumire: "VEN. FIN. DIN AJUSTARI SI PIERDERE DE VALOARE", tip: "P" as const },
  { cod: "7863", denumire: "VEN. FIN. DIN AJUSTARI SI PIERDERE DE VALOARE IMOB. FIN.", tip: "P" as const },
  { cod: "7864", denumire: "VEN. FIN. DIN AJUSTARI SI PIERDERE DE VALOARE ACTIVE CIRC.", tip: "P" as const },
  { cod: "7865", denumire: "VENITURI FINANCIARE DIN AMORT. DIFERENTE TITLURI DE STAT", tip: "P" as const },
  { cod: "794", denumire: "VEN. DIN IMP. PE PROFIT REZULTAT DIN DECONTARILE IN GRUP", tip: "P" as const },
  { cod: "801", denumire: "ANGAJAMENTE ACORDATE", tip: "B" as const },
  { cod: "8011", denumire: "GIRURI SI GARANTII ACORDATE", tip: "B" as const },
  { cod: "8018", denumire: "ALTE ANGAJAMENTE ACORDATE", tip: "B" as const },
  { cod: "802", denumire: "ANGAJAMENTE PRIMITE", tip: "B" as const },
  { cod: "8021", denumire: "GIRURI SI GARANTII PRIMITE", tip: "B" as const },
  { cod: "8028", denumire: "ALTE ANGAJAMENTE PRIMITE", tip: "B" as const },
  { cod: "803", denumire: "ALTE CONTURI IN AFARA BILANTULUI", tip: "B" as const },
  { cod: "8031", denumire: "IMOBILIZARI CORPORALE LUATE CU CHIRIE", tip: "B" as const },
  { cod: "8032", denumire: "VAL. MAT. PRIMITE PT. PRELUCRARE SAU REPARARE", tip: "B" as const },
  { cod: "8033", denumire: "VAL. MAT. PRIMITE IN PASTRARE DAU CUSTODIE", tip: "B" as const },
  { cod: "8034", denumire: "DEBITORI SCOSI DIN ACTIV, URMARITI IN CONTINUARE", tip: "B" as const },
  { cod: "8035", denumire: "STOCURI DE NATURA OBIECTELOR DE INVENTAR DATE ÎN FOLOSINTA", tip: "B" as const },
  { cod: "8036", denumire: "REDEVENTE, LOCATII DE GESTIUNE, CHIRII SI ALTE DATORII ASIM.", tip: "B" as const },
  { cod: "8037", denumire: "EFECTE SCONTATE NEAJUNSE LA SCAD", tip: "B" as const },
  { cod: "8038", denumire: "BUNURI PRIMITE IN ADMINISTRARE, CONCESIUNE SI CU CHIRIE", tip: "B" as const },
  { cod: "8039", denumire: "ALTE VALORI IN AFARA BILANTULUI", tip: "B" as const },
  { cod: "804", denumire: "CERTIFICATE VERZI", tip: "B" as const },
  { cod: "805", denumire: "DOBANZI AFERENTE CONTRACTELOR DE LEASING", tip: "B" as const },
  { cod: "8051", denumire: "DOBANZI DE PLATIT", tip: "B" as const },
  { cod: "8052", denumire: "DOBANZI DE INCASAT", tip: "B" as const },
  { cod: "806", denumire: "CERTIFICATE DE EMISII DE GAZE CU EFECT DE SERA", tip: "B" as const },
  { cod: "807", denumire: "ACTIVE CONTINGENTE", tip: "B" as const },
  { cod: "808", denumire: "DATORII CONTINGENTE", tip: "B" as const },
  { cod: "809", denumire: "CREANTE PRELUATE PRIN CESIONARE", tip: "B" as const },
  { cod: "891", denumire: "BILANT DE DESCHIDERE", tip: "A" as const },
  { cod: "892", denumire: "BILANT DE INCHIDERE", tip: "A" as const },
  { cod: "901", denumire: "DEC. INTERNE PRIVIND CHELTUIELILE", tip: "B" as const },
  { cod: "902", denumire: "DEC. INTERNE PRIVIND PRODUCTIA OBTINUTE", tip: "B" as const },
  { cod: "903", denumire: "DEC. INTERNE PRIVIND DIFERENTELE DE PRET", tip: "A" as const },
  { cod: "921", denumire: "CHELTUIELILE ACTIVITATII DE BAZA", tip: "A" as const },
  { cod: "922", denumire: "CHELTUIELILE ACTIVITATILOR AUXILIARE", tip: "A" as const },
  { cod: "923", denumire: "CHELTUIELI INDIRECTE DE PRODUCTIE", tip: "A" as const },
  { cod: "924", denumire: "CHELTUIELI GENERALE DE ADMINISTRATIE", tip: "A" as const },
  { cod: "925", denumire: "CHELTUIELI DE DESFACERE", tip: "A" as const },
  { cod: "931", denumire: "COSTUL PRODUCTIEI OBTINUTE", tip: "A" as const },
  { cod: "933", denumire: "COSTUL PRODUCTIEI IN CURS DE EXECUTIE", tip: "A" as const },
  { cod: "999", denumire: "CORESPONDENT CONTURI DIN AFARA BILANTULUI", tip: "B" as const },
];

export function getStockRelevantAccounts(): SagaCont[] {
  return SAGA_PLAN_CONTURI.filter(c => {
    const code = c.cod;
    return (
      code.startsWith("3") ||
      code === "401" || code.startsWith("401") ||
      code === "408" ||
      code === "411" || code.startsWith("411") ||
      code === "418" ||
      code.startsWith("442") ||
      code.startsWith("60") ||
      code.startsWith("70")
    );
  });
}

export function searchAccounts(query: string): SagaCont[] {
  const q = query.toLowerCase().trim();
  if (!q) return SAGA_PLAN_CONTURI;
  return SAGA_PLAN_CONTURI.filter(c =>
    c.cod.includes(q) || c.denumire.toLowerCase().includes(q)
  );
}
